# Generated by Django 3.1.1 on 2020-09-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Tech Test', 'Tech Test'), ('Offer', 'Offer'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Applied', max_length=10),
        ),
    ]
