# Generated by Django 3.1.1 on 2020-09-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200925_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
    ]
