# Generated by Django 3.1.1 on 2020-09-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='notes',
        ),
        migrations.AlterField(
            model_name='note',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='portal.job'),
        ),
    ]
