# Generated by Django 3.1.1 on 2020-10-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='notes',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
