# Generated by Django 3.1.1 on 2020-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_call_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
